./main -k "srcIP"
./main -k "srcIP, dstIP"
./main -k "srcIP, dstIP, proto"
./main -k "srcIP, dstIP, dstPort"
./main -k "srcIP, dstIP, dstPort, proto"
./main -k "srcIP, srcPort"
./main -k "srcIP, srcPort, dstIP"
./main -k "srcIP, srcPort, dstIP, proto"
./main -k "srcIP, srcPort, dstIP, dstPort, proto"
