
@pa_atomic("ingress", "ig_md.d_1_hash_s")
@pa_atomic("ingress", "ig_md.d_1_hash_1")
@pa_atomic("ingress", "ig_md.d_1_hash_2")
@pa_atomic("ingress", "ig_md.d_1_hash_3")
@pa_atomic("ingress", "ig_md.d_1_level")
@pa_atomic("ingress", "ig_md.d_1_um_threshold")
@pa_atomic("ingress", "ig_md.d_1_base")
@pa_atomic("ingress", "ig_md.d_1_ss_base")
@pa_atomic("ingress", "ig_md.d_1_est_1")
@pa_atomic("ingress", "ig_md.d_1_est_2")
@pa_atomic("ingress", "ig_md.d_1_est_3")

@pa_atomic("ingress", "ig_md.d_2_hash_s")
@pa_atomic("ingress", "ig_md.d_2_hash_1")
@pa_atomic("ingress", "ig_md.d_2_hash_2")
@pa_atomic("ingress", "ig_md.d_2_hash_3")
@pa_atomic("ingress", "ig_md.d_2_level")
@pa_atomic("ingress", "ig_md.d_2_um_threshold")
@pa_atomic("ingress", "ig_md.d_2_base")
@pa_atomic("ingress", "ig_md.d_2_ss_base")
@pa_atomic("ingress", "ig_md.d_2_est_1")
@pa_atomic("ingress", "ig_md.d_2_est_2")
@pa_atomic("ingress", "ig_md.d_2_est_3")

@pa_atomic("ingress", "ig_md.d_3_hash_s")
@pa_atomic("ingress", "ig_md.d_3_hash_1")
@pa_atomic("ingress", "ig_md.d_3_hash_2")
@pa_atomic("ingress", "ig_md.d_3_hash_3")
@pa_atomic("ingress", "ig_md.d_3_level")
@pa_atomic("ingress", "ig_md.d_3_um_threshold")
@pa_atomic("ingress", "ig_md.d_3_base")
@pa_atomic("ingress", "ig_md.d_3_ss_base")
@pa_atomic("ingress", "ig_md.d_3_est_1")
@pa_atomic("ingress", "ig_md.d_3_est_2")
@pa_atomic("ingress", "ig_md.d_3_est_3")

@pa_atomic("ingress", "ig_md.d_4_hash_s")
@pa_atomic("ingress", "ig_md.d_4_hash_1")
@pa_atomic("ingress", "ig_md.d_4_hash_2")
@pa_atomic("ingress", "ig_md.d_4_hash_3")
@pa_atomic("ingress", "ig_md.d_4_level")
@pa_atomic("ingress", "ig_md.d_4_um_threshold")
@pa_atomic("ingress", "ig_md.d_4_base")
@pa_atomic("ingress", "ig_md.d_4_ss_base")
@pa_atomic("ingress", "ig_md.d_4_est_1")
@pa_atomic("ingress", "ig_md.d_4_est_2")
@pa_atomic("ingress", "ig_md.d_4_est_3")
